## Config file

object_position_limit:
  min: [-0.3, 0.0, -0.3]
  max: [0.3, 0.3, 0.3]


object_orientation_limit: 
  min: [-1.0, -1.0, -1.0]
  max: [1.0, 1.0, 1.0]

camera_distance_limit:
  min: 0.2
  max: 1.0

camera_orientation_limit: 
  min: [-1.0, -1,0]
  max: [1.0, 1.0]


synthetic_image_urls: "config/synthetic_urls.txt"

saved_image_folder: "/home/david/webots/synthetic_data/images/"