## Config file

object_position_limit:
  min: [-0.3, 0.0, -0.3]
  max: [0.3, 0.3, 0.3]


object_orientation_limit: 
  min: [-0.25, -1, -0.25]
  max: [0.25, 1, 0.25]

camera_distance_limit:
  min: 0.2
  max: 0.7

camera_orientation_limit: 
  min: [-0.25, -0.25]
  max: [0.25, 0.25]


camera_size: 224

world_name: "village"


synthetic_image_urls: "config/synthetic_urls.txt"
lighting_file: "config/lighting.txt"

texture_urls: "/usr/local/webots/projects/appearances/protos/"


saved_image_folder: "/home/david/webots/synthetic_data/images/"

start_image_count: 240
dataset_size: 110