## Config file

object_position_limit:
  min: [-1.0, -1.0, -1.0]
  max: [1.0, 1.0, 1.0]


object_rotation_limit: 
  min: [-1.0, -1.0, -1.0]
  max: [1.0, 1.0, 1.0]

camera_distance_limit:
  min: 0.1
  max: 1.0

camera_rotation_limit: 
  min: [-1.0, -1,0]
  max: [1.0, 1.0]
